const db = require('../../config/database');

/**
 * AI History Service
 *
 * Manages persistence and retrieval of AI conversation turns in the
 * ai_chat_history MySQL table.
 *
 * Each turn is stored as a single row with:
 *   - user_id    : the authenticated user (enforces per-user isolation)
 *   - session_id : a UUID generated by the frontend per conversation
 *   - role       : 'user' | 'model' (matches Gemini SDK conventions)
 *   - message    : the raw text of the turn
 *   - tool_used  : the name of the tool called (or null if LLM-only)
 *
 * SECURITY: user_id is always sourced from the verified JWT, never from the
 *           request body, preventing cross-user history access.
 */

/**
 * Save a single conversation turn to the database.
 *
 * @param {number}      userId    - Authenticated user ID from JWT
 * @param {string}      sessionId - Frontend-generated conversation UUID
 * @param {'user'|'model'} role   - Turn author
 * @param {string}      message   - Text content of the turn
 * @param {string|null} toolUsed  - Name of the tool called, or null
 * @returns {Promise<number>} Inserted row ID
 */
const saveMessage = async (userId, sessionId, role, message, toolUsed = null, toolResult = null) => {
    const [result] = await db.query(
        `INSERT INTO ai_chat_history
            (user_id, session_id, role, message, tool_used, tool_result)
         VALUES (?, ?, ?, ?, ?, ?)`,
        [userId, sessionId, role, message, toolUsed, toolResult]
    );
    return result.insertId;
};

/**
 * Retrieve the most recent N turns for a user's session.
 * Results are returned in chronological order (oldest first) so they can be
 * passed directly to the Gemini SDK as conversation history.
 *
 * @param {number} userId
 * @param {string} sessionId
 * @param {number} limit      - Maximum number of turns to retrieve
 * @returns {Promise<Array<{role: string, parts: [{text: string}]}>}
 *   Gemini-compatible history format
 */
const getRecentHistory = async (userId, sessionId, limit = 10) => {
    const [rows] = await db.query(
        `SELECT role, message, tool_used, tool_result, created_at
         FROM ai_chat_history
         WHERE user_id   = ?
           AND session_id = ?
         ORDER BY created_at DESC
         LIMIT ?`,
        [userId, sessionId, limit]
    );

    // Reverse so the array is oldest-first for Gemini context injection
    return rows.reverse().map(row => {
        let textContent = row.message;
        if (row.tool_result) {
            // Inject the hidden JSON context so Gemini remembers what the tool returned
            textContent = `[System Memory: I called tool '${row.tool_used}' and retrieved this JSON data: ${row.tool_result}]\n\n${textContent}`;
        }
        return {
            role:  row.role,
            parts: [{ text: textContent }],
        };
    });
};

/**
 * Delete all conversation history for a specific user session.
 * Used by the DELETE /api/ai/history endpoint.
 *
 * @param {number} userId
 * @param {string} sessionId
 * @returns {Promise<number>} Number of rows deleted
 */
const clearHistory = async (userId, sessionId) => {
    const [result] = await db.query(
        `DELETE FROM ai_chat_history
         WHERE user_id   = ?
           AND session_id = ?`,
        [userId, sessionId]
    );
    return result.affectedRows;
};

/**
 * Get raw history rows for the GET /api/ai/history endpoint.
 * Returns a richer object (with tool_used and timestamps) than getRecentHistory.
 *
 * @param {number} userId
 * @param {string} sessionId
 * @param {number} limit
 * @returns {Promise<Array>}
 */
const getHistoryForDisplay = async (userId, sessionId, limit = 50) => {
    const [rows] = await db.query(
        `SELECT id, role, message, tool_used, created_at
         FROM ai_chat_history
         WHERE user_id    = ?
           AND session_id  = ?
         ORDER BY created_at ASC
         LIMIT ?`,
        [userId, sessionId, limit]
    );
    return rows;
};

module.exports = {
    saveMessage,
    getRecentHistory,
    clearHistory,
    getHistoryForDisplay,
};
